### PR TITLE
Add code of conduct info to agenda

### PR DESCRIPTION
**Pull request by leahecole**

### CODE REVIEW

**Comment by leahecole** [comment]
Great! I don't have merge power, so lmk what I can do to finish this off

**Comment by benjamingr** [comment]
> Great! I don't have merge power, so lmk what I can do to finish this off

@mcollina @jorydotcom can either of you merge this in?

**Comment by ryzokuken** [comment]
Since this is an exact copy of the Contributor Covenant CoC, and I fail to foresee any objections to this, I'm merging this immediately to make sure it sticks around for the longest amount of time possible. Let's hope nobody needs to revert this, but I feel that would be unlikely...

**Comment by ryzokuken** [comment]
@benjamingr oops. I had merge rights as a collaborator, I hope it was okay for me to merge it in.

**Comment by benjamingr** [comment]
@ryzokuken I am unclear on who is allowed to merge things here in terms of governance. On the other hand the CoC already existed in the event subscription itself and obviously in the org.

So your merge seems appropriate tot me but to be fair I have no idea who is allowed to merge things here.

**Comment by ryzokuken** [comment]
I think overall it's okay for collaborators to merge, especially given that we've been granted access and it's not the first time something has been merged by a collaborator to this repository. That said, the nature of the PR makes me uncertain if I was authorized to merge it in, but since it was too obviously okay, I doubt anyone would feel bad about it. Hopefully, I've saved a other a tiny bit of effort 😇

**Comment by mcollina** [comment]
LGTM post-fact

**Pull request merged**
