### PR TITLE
typo: Fix Typo on Collab Summit dates on README.md (Change to reflect accurate date of May 31)

### PR DESCRIPTION
**Pull request by ladyleet**
Changed date from May 30 start to May 31 on README.md

### CODE REVIEW

**Comment by mcollina** [comment]
(this is not a change of date, just a typo fix)

**Comment by ladyleet** [comment]
thx @mcollina i should have been clearer that it was a typo only. :) don't want to confuse anyone!

**Comment by ryzokuken** [comment]
@ladyleet do you think you should change the title for this? I just panicked when I saw this in my notifications and rushed just to see a false alarm. 😅

**Comment by WaleedAshraf** [comment]
sorry for that 😬

**Comment by ladyleet** [comment]
@ryzokuken good idea - updated and sorry for the quick panic attack. :)

**Comment by ladyleet** [comment]
@WaleedAshraf haha whoops! we were changing at the same time!

**Comment by WaleedAshraf** [comment]
much better now 👍 😃

**Comment by ladyleet** [comment]
🎉 thanks @Trott

**Pull request merged**
