### PR TITLE
agenda: adding Open standards & Web compatibility for Vancouver 201808

### PR DESCRIPTION
**Pull request by joyeecheung**
Refs: https://github.com/nodejs/summit/issues/106
Refs: https://github.com/nodejs/summit/issues/100

### CODE REVIEW

**Comment by joyeecheung** [comment]
I noticed that the time slots seem to be a bit off. My first pick was a slot on day 1 but we have 7 slots for 3:30pm on day 1, so the free slots on day 1 don't seem to be actually free to me?

cc @mcollina @chowdhurian @dshaw @ladyleet (organizers listed in this document)

**Comment by devsnek** [comment]
there will be a way to conference in right?

**Comment by mcollina** [comment]
> I noticed that the time slots seem to be a bit off. My first pick was a slot on day 1 but we have 7 slots for 3:30pm on day 1, so the free slots on day 1 don't seem to be actually free to me?

Those are for a "table" session in the main room, similar to last year.

**Comment by mcollina** [comment]
@devsnek that depends on the session organizer  to set that up. Ideally yes.

**Comment by joyeecheung** [comment]
I'll try to set it up (are we still going to use Zoom this time?)

**Pull request merged**
