### PR TITLE
Add myself to attendee list

### PR DESCRIPTION
**Pull request by ry**
@MylesBorins

### CODE REVIEW

**Comment by maddhruv** [comment]
BTW the list is alphabetically ordered :grinning:
Oh! he is the father :heart_eyes:

**Comment by benjamingr** [comment]
@ry would love to discuss the promises stuff I'm (potentially) being annoying aboutw.

**Comment by ry** [comment]
@benjamingr Hey I just saw this - sorry I missed you today - yes I would love to chat. I'll be in Berlin until Sunday afternoon  - so hopefully we'll get a chance.

**Comment by benjamingr** [comment]
@ry I'm here until Monday and also in the summit today - also welcome to ping me at benjamingr@gmail.com

**Pull request merged**
