### PR TITLE
doc: mention travel funds

### PR DESCRIPTION
**Pull request by joyeecheung**

### CODE REVIEW

**Comment by joyeecheung** [comment]
I am also raising a PR in the Node core onboarding guide (https://github.com/nodejs/node/pull/16079) that mention the collaboration summit. Just making sure people are aware of it so they could prepare in advance and attend.

**Comment by joyeecheung** [comment]
@Trott Fixed, thanks!

**Comment by joyeecheung** [comment]
I assume we use the merge button here. Let me know if I've got it wrong.

**Comment by gibfahn** [comment]
>I assume we use the merge button here. Let me know if I've got it wrong.

The `Squash and merge` button? I don't think it really matters for this repo, but in general disabling the `Merge Pull Request` button, and just leaving `Squash and Merge` and `Rebase and Merge` seems like a good way to go in repos that aren't `nodejs/node`.

**Comment by joyeecheung** [comment]
@gibfahn SGTM, though I am not good enough with Github to know how to do that.

**Comment by gibfahn** [comment]
>@gibfahn SGTM, though I am not good enough with Github to know how to do that.

You'd go to https://github.com/nodejs/summit/settings and untick the `Allow merge commits` button (leaving the other two ticked), like so:

image

**Comment by ljharb** [comment]
fwiw I always only use the merge commit setting; GitHub's squashmerge and rebasemerge leave orphaned origin/pr/ refs in the git log (if you have enabled fetching of those).

Better is to rebase the fork's branch, push it up, and *then* merge commit or fast-forward merge (altho it's less convenient)

**Comment by joyeecheung** [comment]
@gibfahn Done, thanks for the help!

**Comment by joyeecheung** [comment]
@gibfahn I meant, for this repo. Not quite sure about others, probably best let the owners decide.

**Comment by gibfahn** [comment]
>fwiw I always only use the merge commit setting; GitHub's squashmerge and rebasemerge leave orphaned origin/pr/ refs in the git log (if you have enabled fetching of those).

@ljharb  Interesting reason to use merge commits. Does setting `git config --global fetch.prune true` fix that or does GitHub store them indefinitely (or until the person who raised the PR deletes their branch)?

I just have [an alias](https://github.com/gibfahn/dot/blob/cdc139f0fb9e1584206453c796112954ab5f3092/dotfiles/.config/git/config#L45-L46) for fetching PR branches instead of bulk fetching, so I hadn't noticed.

**Comment by ljharb** [comment]
It's stored indefinitely, no matter what happens to the branch, since it's a ref and not a branch.

**Comment by gibfahn** [comment]
>It's stored indefinitely, no matter what happens to the branch, since it's a ref and not a branch.

@ljharb Ah, I see, so they're branches in a different [git namespace](https://git-scm.com/docs/gitnamespaces)? I didn't know that was a thing.

Assuming you're using something based on the original Bert Belder gist, it sounds like you can delete PR branches with: https://gist.github.com/piscisaureus/3342247#gistcomment-1763247, no idea if that actually works.

**Pull request merged**
