### PR TITLE
Confirming Trevor Livingston as an invited speaker

### PR DESCRIPTION
**Pull request by jasnell**

### CODE REVIEW

**Comment by Trott** [comment]
I'm surprised we're scheduling talks for the summit portion, especially talks on unspecified topics.

**Comment by jasnell** [comment]
Just one. 20 minutes.

**Comment by Trott** [comment]
> Just one. 20 minutes.

Not trying to troll or second-guess but am trying to get an idea of the process here: 

Who makes these decisions? 

Is it just a case of "James (or someone else) stepped up to do the hard and thankless work of organizing, so they kinda get to decide format etc. Deal with it."? 

If so, that's *totally* fair. (Big fan of "whoever is doing the work gets to make the decisions".) 

If not, how was this decided?

(Also, to be clear: I have no problems at all whatsoever with the speaker. Have talked with him a few times in the past and as far as I can tell they're 💯. Will likely enjoy whatever they have to say. Doesn't take away from the surprised element here, though.)

**Comment by jasnell** [comment]
> stepped up to do the ... work of organizing

Yes, that.

The intent here is to interject a little more something we've tended to lack: perspective of Node.js users who are building real businesses on top of the platform we're collectively building.

**Comment by MylesBorins** [comment]
@jasnell while i think it is great that we have scheduled content it seems really odd to confirm / reach out to the speaker before reaching consensus with the group at large.

Did I miss a thread where scheduling this content was discussed? If not this is a pretty heavy handed way to schedule content.

**Comment by hackygolucky** [comment]
We aren't going to have a microphone, @jasnell afaik for the collaborator's summit because the last two didn't really take advantage of one. Coordinating with the other folks who are helping with organizing this, including the Events staff setting up the venue, will help us succeed together. 

I think I missed a thread where we were talking about having some talks, sorry. So many issues to follow :-/

**Comment by jasnell** [comment]
We will work it out.

**Comment by jasnell** [comment]
Very well.
/cc @dshaw .... just as a heads up.

**Comment by dshaw** [comment]
🙏  Sounds good. Run through the process. Let me know how I can help.

**Comment by bengl** [comment]
> The intent here is to interject a little more something we've tended to lack: perspective of Node.js users who are building real businesses on top of the platform we're collectively building.

Can we put out an invitation to participate in the summit directed non-node-core folks from those companies in order to get a better representation of their needs?

**Comment by jasnell** [comment]
Feel free to close this if it's not what folks want. I was working on the agenda because no one else was. Given that there are now others who want to help organize, I'm happy to hand it over.

**Pull request closed without merging**
